[[DeviceList]]
  Name = "Laptop-Device"
  ProfileName = "Laptop-Device-Profile"
  Description = "Example of Simple Device"
  Labels = [ "industrial" ]
  [DeviceList.Protocols]
  [DeviceList.Protocols.other]
    Address = "simple01"
    Port = "300"
  [[DeviceList.AutoEvents]]
    Interval = "5s"
    OnChange = false
    SourceName = "temperature"
